name: WorldTag
version: '1.2.2'
main: worldtag.example.worldTag.WorldTag
api-version: '1.21'
authors: [ Nice_Cam_ Luniverse_vix ]
description: A custom World Tag plugin for Luniverse_vix's Slimefun Server
website: https://iar.lvix.top/
